from django.urls import path

from service.access import admin_required, team_required
from service.views import (
    agenda,
    aprovar_orcamento,
    atualizar_status_ordem_servico,
    buscar_endereco_cep,
    buscar_lead_dados,
    buscar_mapa_orcamento,
    cadastrar_cliente_orcamento,
    catalogo,
    concluir_orcamento,
    concluir_ordem_servico,
    deletar_cliente,
    deletar_orcamento,
    deletar_produto,
    detalhe_orcamento,
    detalhe_ordem_servico,
    editar_cliente,
    editar_orcamento,
    editar_ordem_servico,
    editar_produto,
    editar_tecnico,
    gerar_orcamento_pdf,
    listar_clientes,
    listar_leads,
    listar_orcamentos,
    listar_ordens_servico,
    listar_tecnicos,
    nova_categoria,
    novo_cliente,
    novo_lead,
    novo_orcamento,
    nova_ordem_servico,
    novo_produto,
    novo_tecnico,
    teste,
    vincular_cliente_orcamento,
)
from service.views.auth import ServiceLoginView, painel_inicial, sair

urlpatterns = [
    path("", painel_inicial, name="inicio"),
    path("login/", ServiceLoginView.as_view(), name="login"),
    path("logout/", sair, name="logout"),
    path("teste/", admin_required(teste), name="teste"),
    path("leads/", admin_required(listar_leads), name="leads"),
    path("leads/novo/", admin_required(novo_lead), name="novo_lead"),
    path("leads/<int:pk>/dados/", admin_required(buscar_lead_dados), name="buscar_lead_dados"),
    path("catalogo/", admin_required(catalogo), name="catalogo"),
    path("agenda/", team_required(agenda), name="agenda"),
    path("ordens-servico/", team_required(listar_ordens_servico), name="ordens_servico"),
    path("ordens-servico/nova/", admin_required(nova_ordem_servico), name="nova_os"),
    path("ordens-servico/<int:pk>/status/", team_required(atualizar_status_ordem_servico), name="atualizar_status_os"),
    path("ordens-servico/<int:pk>/", team_required(detalhe_ordem_servico), name="os_detalhe"),
    path("ordens-servico/<int:pk>/editar/", admin_required(editar_ordem_servico), name="editar_os"),
    path("ordens-servico/<int:pk>/concluir/", team_required(concluir_ordem_servico), name="concluir_os"),
    path("tecnicos/", admin_required(listar_tecnicos), name="tecnicos"),
    path("tecnicos/novo/", admin_required(novo_tecnico), name="novo_tecnico"),
    path("tecnicos/<int:pk>/editar/", admin_required(editar_tecnico), name="editar_tecnico"),
    path("clientes/", admin_required(listar_clientes), name="clientes"),
    path("clientes/novo/", admin_required(novo_cliente), name="novo_cliente"),
    path("clientes/<int:pk>/editar/", admin_required(editar_cliente), name="editar_cliente"),
    path("clientes/<int:pk>/deletar/", admin_required(deletar_cliente), name="deletar_cliente"),
    path("catalogo/novo/", admin_required(novo_produto), name="novo_produto"),
    path("catalogo/<int:pk>/editar/", admin_required(editar_produto), name="editar_produto"),
    path("catalogo/<int:pk>/deletar/", admin_required(deletar_produto), name="deletar_produto"),
    path("catalogo/categorias/nova/", admin_required(nova_categoria), name="nova_categoria"),
    path("orcamentos/", admin_required(listar_orcamentos), name="orcamentos"),
    path("orcamentos/novo/", admin_required(novo_orcamento), name="novo_orcamento"),
    path("orcamentos/cep/<str:cep>/", admin_required(buscar_endereco_cep), name="buscar_endereco_cep"),
    path("orcamentos/<int:pk>/", admin_required(detalhe_orcamento), name="orcamento_detalhe"),
    path("orcamentos/<int:pk>/editar/", admin_required(editar_orcamento), name="editar_orcamento"),
    path("orcamentos/<int:pk>/mapa/", admin_required(buscar_mapa_orcamento), name="buscar_mapa_orcamento"),
    path("orcamentos/<int:pk>/pdf/", admin_required(gerar_orcamento_pdf), name="gerar_orcamento_pdf"),
    path("orcamentos/<int:pk>/concluir/", admin_required(concluir_orcamento), name="concluir_orcamento"),
    path(
        "orcamentos/<int:pk>/cadastrar-cliente/",
        admin_required(cadastrar_cliente_orcamento),
        name="cadastrar_cliente_orcamento",
    ),
    path(
        "orcamentos/<int:pk>/vincular-cliente/",
        admin_required(vincular_cliente_orcamento),
        name="vincular_cliente_orcamento",
    ),
    path("orcamentos/<int:pk>/aprovar/", admin_required(aprovar_orcamento), name="aprovar_orcamento"),
    path("orcamentos/<int:pk>/deletar/", admin_required(deletar_orcamento), name="deletar_orcamento"),
]
