from django.urls import path

from service.views import (
    agenda,
    aprovar_orcamento,
    atualizar_status_ordem_servico,
    buscar_endereco_cep,
    buscar_lead_dados,
    buscar_mapa_orcamento,
    cadastrar_cliente_orcamento,
    catalogo,
    configuracoes,
    concluir_orcamento,
    concluir_ordem_servico,
    deletar_cliente,
    deletar_orcamento,
    deletar_produto,
    detalhe_orcamento,
    detalhe_ordem_servico,
    editar_cliente,
    editar_orcamento,
    editar_ordem_servico,
    editar_produto,
    editar_tecnico,
    gerar_orcamento_pdf,
    inicio,
    listar_clientes,
    listar_leads,
    listar_orcamentos,
    listar_ordens_servico,
    listar_tecnicos,
    nova_categoria,
    novo_cliente,
    novo_lead,
    novo_orcamento,
    nova_ordem_servico,
    novo_produto,
    novo_tecnico,
    teste,
    vincular_cliente_orcamento,
)

urlpatterns = [
    path("", inicio, name="inicio"),
    path("teste/", teste, name="teste"),
    path("leads/", listar_leads, name="leads"),
    path("leads/novo/", novo_lead, name="novo_lead"),
    path("leads/<int:pk>/dados/", buscar_lead_dados, name="buscar_lead_dados"),
    path("catalogo/", catalogo, name="catalogo"),
    path("configuracoes/", configuracoes, name="configuracoes"),
    path("agenda/", agenda, name="agenda"),
    path("ordens-servico/", listar_ordens_servico, name="ordens_servico"),
    path("ordens-servico/nova/", nova_ordem_servico, name="nova_os"),
    path("ordens-servico/<int:pk>/status/", atualizar_status_ordem_servico, name="atualizar_status_os"),
    path("ordens-servico/<int:pk>/", detalhe_ordem_servico, name="os_detalhe"),
    path("ordens-servico/<int:pk>/editar/", editar_ordem_servico, name="editar_os"),
    path("ordens-servico/<int:pk>/concluir/", concluir_ordem_servico, name="concluir_os"),
    path("tecnicos/", listar_tecnicos, name="tecnicos"),
    path("tecnicos/novo/", novo_tecnico, name="novo_tecnico"),
    path("tecnicos/<int:pk>/editar/", editar_tecnico, name="editar_tecnico"),
    path("clientes/", listar_clientes, name="clientes"),
    path("clientes/novo/", novo_cliente, name="novo_cliente"),
    path("clientes/<int:pk>/editar/", editar_cliente, name="editar_cliente"),
    path("clientes/<int:pk>/deletar/", deletar_cliente, name="deletar_cliente"),
    path("catalogo/novo/", novo_produto, name="novo_produto"),
    path("catalogo/<int:pk>/editar/", editar_produto, name="editar_produto"),
    path("catalogo/<int:pk>/deletar/", deletar_produto, name="deletar_produto"),
    path("catalogo/categorias/nova/", nova_categoria, name="nova_categoria"),
    path("orcamentos/", listar_orcamentos, name="orcamentos"),
    path("orcamentos/novo/", novo_orcamento, name="novo_orcamento"),
    path("orcamentos/cep/<str:cep>/", buscar_endereco_cep, name="buscar_endereco_cep"),
    path("orcamentos/<int:pk>/", detalhe_orcamento, name="orcamento_detalhe"),
    path("orcamentos/<int:pk>/editar/", editar_orcamento, name="editar_orcamento"),
    path("orcamentos/<int:pk>/mapa/", buscar_mapa_orcamento, name="buscar_mapa_orcamento"),
    path("orcamentos/<int:pk>/pdf/", gerar_orcamento_pdf, name="gerar_orcamento_pdf"),
    path("orcamentos/<int:pk>/concluir/", concluir_orcamento, name="concluir_orcamento"),
    path(
        "orcamentos/<int:pk>/cadastrar-cliente/",
        cadastrar_cliente_orcamento,
        name="cadastrar_cliente_orcamento",
    ),
    path("orcamentos/<int:pk>/vincular-cliente/", vincular_cliente_orcamento, name="vincular_cliente_orcamento"),
    path("orcamentos/<int:pk>/aprovar/", aprovar_orcamento, name="aprovar_orcamento"),
    path("orcamentos/<int:pk>/deletar/", deletar_orcamento, name="deletar_orcamento"),
]
