from service.views.catalogo import (
    catalogo,
    deletar_cliente,
    editar_cliente,
    listar_clientes,
    listar_leads,
    nova_categoria,
    novo_cliente,
    novo_lead,
)
from service.views.comum import inicio, teste
from service.views.orcamentos import (
    aprovar_orcamento,
    buscar_cliente_dados,
    buscar_endereco_cep,
    buscar_mapa_orcamento,
    cadastrar_cliente_orcamento,
    concluir_orcamento,
    deletar_orcamento,
    detalhe_orcamento,
    editar_orcamento,
    gerar_orcamento_pdf,
    listar_orcamentos,
    novo_orcamento,
    vincular_cliente_orcamento,
)
from service.views.ordens import (
    agenda,
    concluir_ordem_servico,
    detalhe_ordem_servico,
    editar_ordem_servico,
    editar_tecnico,
    listar_ordens_servico,
    listar_tecnicos,
    nova_ordem_servico,
    novo_tecnico,
)
from service.views.produtos import deletar_produto, editar_produto, novo_produto

__all__ = [
    "agenda",
    "aprovar_orcamento",
    "buscar_cliente_dados",
    "buscar_endereco_cep",
    "buscar_mapa_orcamento",
    "cadastrar_cliente_orcamento",
    "catalogo",
    "concluir_orcamento",
    "concluir_ordem_servico",
    "deletar_cliente",
    "deletar_orcamento",
    "deletar_produto",
    "detalhe_orcamento",
    "detalhe_ordem_servico",
    "editar_cliente",
    "editar_orcamento",
    "editar_ordem_servico",
    "editar_produto",
    "editar_tecnico",
    "gerar_orcamento_pdf",
    "inicio",
    "listar_clientes",
    "listar_leads",
    "listar_orcamentos",
    "listar_ordens_servico",
    "listar_tecnicos",
    "nova_categoria",
    "novo_cliente",
    "novo_lead",
    "novo_orcamento",
    "nova_ordem_servico",
    "novo_produto",
    "novo_tecnico",
    "teste",
    "vincular_cliente_orcamento",
]
