# Generated by Django 6.0.4 on 2026-05-07 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_categoria_catalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=120, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('administrador_executa', models.BooleanField(default=False, help_text='Marque quando o administrador ou dono executar o servico.')),
                ('titulo', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('data_agendada', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('valor', models.FloatField(default=0)),
                ('instrucoes', models.TextField(blank=True, null=True)),
                ('checklist', models.TextField(blank=True, null=True)),
                ('observacoes_execucao', models.TextField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='service.cliente')),
                ('orcamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordem_servico', to='service.orcamento')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='service.tecnico')),
            ],
            options={
                'ordering': ['data_agendada', 'hora_inicio', 'id'],
            },
        ),
    ]
