# Generated by Django 6.0.4 on 2026-05-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_tecnico_ordemservico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=120, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=120, null=True)),
                ('bairro', models.CharField(blank=True, max_length=120, null=True)),
                ('cidade', models.CharField(blank=True, max_length=120, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('aguardando', 'Aguardando'), ('convertido', 'Convertido')], default='novo', max_length=20)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('indicacao', 'Indicacao'), ('site', 'Site'), ('outro', 'Outro')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_origem', to='service.cliente')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='service.lead'),
        ),
    ]
