# Generated by Django 6.0.4 on 2026-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_lead_orcamento_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_catalog',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='catalogo/'),
        ),
    ]
