# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0011_tecnico_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
