# Generated by Django 6.0.4 on 2026-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_multiplicador_orcamento_descricao_aplica_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionalorcamento',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='adicionalorcamento',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='adicionalorcamento',
            name='tipo_valor',
            field=models.CharField(blank=True, choices=[('fixo', 'Valor fixo'), ('percentual', 'Percentual')], default='fixo', max_length=20),
        ),
    ]
