# Generated by Django 6.0.4 on 2026-07-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_adicionalorcamento_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
