# Generated by Django 6.0.4 on 2026-07-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_merge_0012_lead_observacoes_0019_adicionalorcamento_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('indicacao', 'Indicação'), ('site', 'Site'), ('outro', 'Outro')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='administrador_executa',
            field=models.BooleanField(default=False, help_text='Marque quando o administrador ou dono executar o serviço.'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
    ]
