# Generated by Django 6.0.4 on 2026-07-22 13:29

import service.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_cliente_cnpj_cliente_observacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_catalog',
            name='imagem',
            field=models.ImageField(blank=True, null=True, storage=service.storages.catalog_image_storage, upload_to='catalogo/'),
        ),
    ]
